version: '3.7'

volumes:
  redis:
  postgres-data:
    driver: local
  ecommerce-gems:
    external: true

services:
  db:
    image: postgres:9.6.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'testing'
  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  app:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
      - ecommerce-gems:/ecommerce-gems
    ports:
      - 3000:3000
    links:
      - db
      - redis
    env_file:
      - .env
