development:
  forest_env_secret: 07a87e7808129fc2723a02a14f53081df9e3fbc763e257b0e63509a0521c98f6
  forest_auth_secret: da4c26a602bc9f3aac71abd18237f0c4fe99eb28ef22ef5ccba0efdf0d5a1c1940624657bf234ab55993045a348fc0f7
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
